plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-capybara

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "node_modules/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Layout/LineLength:
  Max: 100
  Exclude:
    - "Gemfile"
    - "config/environments/production.rb"
    - "config/initializers/filter_parameter_logging.rb"
    - "app/controllers/application_controller.rb"

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/ClassStructure:
  Enabled: true
  ExpectedOrder:
    - module_inclusion
    - constants
    - association
    - public_attribute_macros
    - public_delegate
    - macros
    - public_class_methods
    - initializer
    - public_methods
    - protected_attribute_macros
    - protected_methods
    - private_attribute_macros
    - private_delegate
    - private_methods

Metrics/BlockLength:
  CountAsOne:
    - array
    - hash
    - heredoc

Metrics/MethodLength:
  CountAsOne:
    - array
    - hash
    - heredoc

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: true
  Max: 4

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

Style/HashAsLastArrayItem:
  EnforcedStyle: no_braces

Style/Lambda:
  EnforcedStyle: literal

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
